### ISSUE TITLE
Add support for frontend-login

### ISSUE THREAD

**Issue by JW301** [cdaecke/md_saml#1]
As far as I can tell, there is no working extension that provides support for frontend login in current Typo3 versions. Would be great to see this new extension implement it.

**Comment by cdaecke** [comment]
The frontend login is implemented in https://github.com/cdaecke/md_saml/commit/a95c8e3d90de4124cecb04ef20e276b1d736dee4

Would you like to give it a try?

Please be aware, that the typoscript configuration has changed. Configure frontend login in `plugin.tx_mdsaml.settings.fe_users.saml...` and TYPO3 login in `plugin.tx_mdsaml.settings.be_users.saml...`.

**Comment by cdaecke** [comment]
Version 2.0.0 is released, which supports frontend login as well.
