### ISSUE TITLE
Missing handling of requestToken in TYPO3 v12

### ISSUE THREAD

**Issue by julianhofmann** [cdaecke/md_saml#10]
The return to TYPO3 (or the authentication there) fails due to the missing requestToken in TYPO3 v12.

* [Breaking: #97305 - Introduce CSRF-like login token](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97305-IntroduceCSRF-likeLoginToken.html)

However, this is possibly already being clarified at StackOverflow....
https://stackoverflow.com/questions/77866083/custom-backend-authentication-service-in-typo3-v12

**Comment by cdaecke** [comment]
@julianhofmann Thanks a lot for pointing this out!
A first fix is added.

The backend login is working now with TYPO3 v12, but I get redirected to `/typo3/login`. Only when I remove the `login` from the Url afterwards, I get the TYPO3 backend. Don't know why this happens and have to investigate a little more.

If you have any ideas, I would be happy, to get pointed into the right direction ;-)

**Comment by cdaecke** [comment]
I did some research now.
Debugging the returning requests from the ADFS server shows the following:

1. Post request form ADFS server back to the TYPO3 URL. It sets a cookie and redirects.
<img width="849" alt="01" src="https://github.com/cdaecke/md_saml/assets/2102444/69303eb0-4992-4cc9-9eb7-613b6284846b">

2. Request to the TYPO3 backend. This deletes the cookie (is this correct??) and redirects again.
<img width="848" alt="02" src="https://github.com/cdaecke/md_saml/assets/2102444/d628aa6f-9c01-44dc-aef5-9e6637d2fa31">

3. Request to the login screen, creating the correct login with setting the cookie 
<img width="848" alt="03" src="https://github.com/cdaecke/md_saml/assets/2102444/5566a8f2-2aeb-4562-a337-264421ca7799">

After removing the `/login` from the URL, the TYPO3 backend is shown correctly.

@julianhofmann I have no clue what happens here. Do you know, what goes wrong? Any hint is appreciated very much!

**Comment by ghanshyam-drc** [comment]
Just hint, im not sure. This could be issue with PSR. It has no explicit interface so it wont send Set-Cookie with server response header. Possible solution is either use some external lib which allow to send secure cookie (Se-cookie) with response header or build own header.

**Comment by cdaecke** [comment]
Sometimes I have to have a break and do other things. Just in this moments I get new ideas and this time I had to remember the following from my own documentation: `In "LocalConfiguration.php" or "AdditionalConfiguration.php" the "['BE']['cookieSameSite']"" must be set to "lax"`. After doing so, the login worked perfektly fine! :-)
