### ISSUE TITLE
Cookie deleted for backend TYPO3 v12

### ISSUE THREAD

**Issue by ghanshyam-drc** [cdaecke/md_saml#12]
I have implemented login with oAuth, but its not allow me to login TYPO3 backend. When used authorised and redirect back to TYPO3 backend, its shows no error. 

Url shows something like this: https://t3v-12.ddev.site//typo3/index.php?loginProvider=1648123062&login-provider=md_saml&login_status=login&acs

Also carry SAMLResponse and when you decode response, it shows status success and return attributes back.

See:
![image](https://github.com/cdaecke/md_saml/assets/65883848/809580c7-7f74-4b90-843c-507f24c574dd)

Maybe cookie can be issue? when I check developer tool response. TYPO3 backend cookie shows deleted
![image](https://github.com/cdaecke/md_saml/assets/65883848/d1ef83e2-183c-4f95-837f-3d7b43eaa22c)

If I try manually set cookie for valid BE user it lead error you mention in troubleshooting section. I have checked this and applied solution: https://github.com/cdaecke/md_saml?tab=readme-ov-file#troubleshooting but no luck, getting same error.

Any hint for fix?

**Comment by cdaecke** [comment]
Thanks for reporting. This is a know issue (see #10) for TYPO3 v12 at the moment.

Hoping to solve this soon. Any help is appreciated.

**Comment by cdaecke** [comment]
Could you please verify, whether you have done the following setting in TYPO3:

    $GLOBALS['TYPO3_CONF_VARS']['BE']['cookieSameSite'] = 'lax';

**Comment by cdaecke** [comment]
I have just release a new version of the extension which works with TYPO3 v12 for me.

Is this working for you as well?

**Comment by ghanshyam-drc** [comment]
Seems new release fix issue with `$GLOBALS['TYPO3_CONF_VARS']['BE']['cookieSameSite'] = 'lax';`!
