### ISSUE TITLE
Modernize handling of POST/GET

### ISSUE THREAD

**Issue by julianhofmann** [cdaecke/md_saml#14]
Currently, access is via `GeneralUtilitiy`-methods (or even directly to the global `$_POST` array). 
The GeneralUtilitiy methods have been deprecated since TYPO3 v12. Accessing `$_POST` directly has long been unsightly.

**Solution:**

> Retrieving arguments from the request object. An instance of the PSR-7 ServerRequestInterface is handed over to controllers by TYPO3 Core's PSR-15 \TYPO3\CMS\Core\Http\RequestHandlerInterface and middleware implementations, and is available in various related scopes like the frontend \TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer.
> 
> Typical code:
> 
> ```
> use TYPO3\CMS\Core\Utility\GeneralUtility;
> 
> // Before
> $value = GeneralUtility::_POST('tx_scheduler');
> 
> // After
> $value = $request->getParsedBody()['tx_scheduler']);
> ```

* [Deprecation: #100053 ](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Deprecation-100053-GeneralUtility_GP.html)- GeneralUtility::_GP() 
* [Deprecation: #99633](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.2/Deprecation-99633-GeneralUtilityPOST.html) - GeneralUtility::_POST()

**Comment by cdaecke** [comment]
I have noticed the deprecation of `GeneralUtility::_GP()`, `GeneralUtility::_GET()` etc. but I am not sure how to migrate without using the global `$_GET` or `$_POST` array.

As far as I am concerned the `ServerRequestInterface` in `$GLOBALS['TYPO3_REQUEST']` is not available for example in the `SamlAuthService` class, so I can't do something like that:

    $this->getRequest()->getQueryParams()['key'];

    protected function getRequest(): ServerRequestInterface
    {
        return $GLOBALS['TYPO3_REQUEST'];
    }

@julianhofmann What would you propose to do?

**Comment by bmack** [comment]
Some notes:

* The wrappers `GeneralUtility::_GP()` etc. were nowadays really wrappers for `$_GET` and `$_POST`, so you could just replace them with the superglobals.
* The SamlToolKit under the hood uses $_GET and $_POST and does not use PSR-7 (which is a bit sad), so we need to rely on them still
* In TYPO3 v12, the $request is available in the authInfo array (property `request`), for TYPO3 v11 compatibility I had to use a custom middleware to set $GLOBALS['TYPO3_REQUEST'] in my own SAMLauth extensions

**Comment by cdaecke** [comment]
@bmack Thanks, for pointing that out, very appreciated! The changes are attached to this issue.

If you both (@julianhofmann and @bmack) have any suggestions on how to make this extension even better, please let me know. I am always very happy to improve the code, ore make the handling of the extension more easy.

**Comment by bmack** [comment]
@cdaecke if you're at a TYPO3 event, I can show you my approaches in person, on how I set up configuration of SAML on a per-site basis, do SLO etc.
