### ISSUE TITLE
TYPO3 11.5 SAML ERROR The response was received at

### ISSUE THREAD

**Issue by amrvka** [cdaecke/md_saml#15]
Hello developer,

first of all - thank you for this SAML plugin! it looks nice and the parameters are readable and understandable at all.
also the METADATA Generator is genius! i did not knew it before and then during debugging i read until the end of your docs :-)

Its easy to configure and i tlooks like it does what it should - but except one thing which is sadly the most important part.

i use Azure AD / Entra ID instead of ADFS (we used it before) and everthing looks like it correctly configured so there's no
difference between ADFS and Entra ID.

So the problem is just the referrer.
1. i click at the BACKEND on log-in:
POST https://my.url.domain/typo3/login?loginProvider=1648123062 HTTP/1.1

2. i get the respone to authenticate in Entra ID:
Location: https://login.microsoftonline.com/<mytenantid>/saml2?SAMLRequest=rVNNj9owFLzz....

3. Entra ID authenticates: and sends the ACS Link back to the user
AssertionConsumerServiceURL="https://my.url.domain/typo3/index.php?loginProvider=1648123062&login-provider=md_saml&login_status=login&acs"

4. The Browser sends a POST Request to:
POST https://my.url.domain/typo3/index.php?loginProvider=1648123062&login-provider=md_saml&login_status=login&acs
with every good informations.

5. TYPO3 11.5 says:
The response was received at https://my.url.domain/index.php instead of https://my.url.domain/typo3/index.php?loginProvider=1648123062&login-provider=md_saml&login_status=login&acs

and that is what i can't find.
knowwhere is the information for the Typo3 frontend if this is meant here.
Your SAML plugin sends correct info to the browser, the Entra ID sends everything correct back.
Why has your plugin (or the module php-saml?) the wrong information?

Can you help me please?

Best regards
Andreas

**Comment by cdaecke** [comment]
Which version of the extension are you using?

For the time being, please use [version 2](https://github.com/cdaecke/md_saml/releases/tag/2.0.0), because version 3 is not working correctly yet.

**Comment by amrvka** [comment]
hello, thank you for your fast response.
i tried v 3.01 first... now i changed to v2.0.0 as requested. (in typo3 11.5 -> extension manager -> view other releases, install v2.0.0

i cleared all caches.

But the error remains sadly the same:

_The response was received at https://my.url.domain/index.php instead of https://my.url.domain/typo3/index.php?loginProvider=1648123062&login-provider=md_saml&login_status=login&acs_

--------------------------------------------
the one thing, i did not do but was given in your documentation, is : create the EVENT in Typo3.
https://github.com/cdaecke/md_saml#change-user-event

i do not have a customized extension, and i don't know what i should write into "namespace XXX\XXX\EventListener;"
instead of the XXX

The code seems to be adding users to groups, which is not necessary at the moment for me.

Is this Event a requirement?


your application (SP) and Entra ID (IDP) do everything correct, every value is correct, why do i this error? how can i debug this incident?

**Comment by amrvka** [comment]
can i help you anyhow debugging this topic? is there any possibility enabling debugging, on PHP or on OneLogin (php-saml) side? Sadly, i am not a PHP developer, i just can activate error_log :)
kann ich etwas beitragen? das Plugin bzw. die Config Datei ist wirklich gut geschrieben.

I would really appretiate it if it works on my side.

**Comment by cdaecke** [comment]
It is hard to say, what goes wrong. I assume, that you have double checked all configuration twice? Do you get all the date of the logged in account back correctly?

One start of debugging could be the point of your error message: `Resources/Libraries/vendor/onelogin/php-saml/src/Saml2/Response.php` on line 289.

You do not need to implement an event listener.

**Comment by cdaecke** [comment]
I dived now deeper into the code of the onelogin library.

Am I right, that the login is working for you, if you change the configuration of `plugin.tx_mdsaml.settings.saml.strict` to `false`?
ATTENTION: This is not recommended for production systems!
https://github.com/cdaecke/md_saml/blob/d0deab6b88f058ae1c3bbb41b484b15b1d3d45ff/Configuration/TypoScript/setup.typoscript#L78-L82

Please activate `plugin.tx_mdsaml.settings.saml.debug` for more debugging infos and adjust your your settings accordingly.
https://github.com/cdaecke/md_saml/blob/d0deab6b88f058ae1c3bbb41b484b15b1d3d45ff/Configuration/TypoScript/setup.typoscript#L84-L85

You might need to remove the "index.php" from `plugin.tx_mdsaml.settings.be_users.saml.sp.entityId`?
Be aware, that you might need to update the configuration of your IdP after changing settings, in order to validate everything correctly.

**Comment by cdaecke** [comment]
By the way: Please update the extension to the latest version.

**Comment by treknuts** [comment]
I had the same issue and needed to add `/typo3` to the `plugin.tx_mdsaml.settings.mdsamlSpBaseUrl` value. It should look something like `plugin.tx_mdsaml.settings.mdsamlSpBaseUrl = https://example.com/typo3` if you're trying to do backend authentication.

Unrelated to this issue, but can you, @cdaecke, expand on why Typo3 v11 should use 2.0.0? I am currently running Typo3 v11.5.36 with 3.0.5 and haven't experienced any issues. Other than forgetting to turn off `updateIfExist`.

**Comment by cdaecke** [comment]
@treknuts Version 3.0.0 was intended to work with TYPO3 v12, but didn't and I am not sure if it works with TYPO3 v11. So the first working version for TYPO3 v12 is v3.0.2 and the tested version for TYPO3 v11 is v2.0.0.
