### ISSUE TITLE
Exception in `getRootPageId()` with `languages` and different TLDs

### ISSUE THREAD

**Issue by web-it-solutions** [cdaecke/md_saml#17]
Hello,
In [SettingsService.php line 132](https://github.com/cdaecke/md_saml/blob/master/Classes/Service/SettingsService.php#L132) the rootPageId is fetched only if the host of the base url equals the `$siteUrl` (TYPO3_HOST_ONLY).

In case you have a multilanguage setup with different top level domains mapped to the language(s) the service will not find a valid rootPageId and the exception `1648646492` is thrown.

Would it be a good idea to do the following in the foreach loop?

`foreach ($site->getLanguages() as $language) {
    if ($language->getBase()->getHost() == $siteUrl) {
         return $site->getRootPageId();
    }
}`

I would start a PR if you agree with the mentioned solution!

Thanks for bringing this to TYPO3 12.

**Comment by cdaecke** [comment]
Hello,

sounds like a good idea.
Pull request is very welcome!

**Comment by cdaecke** [comment]
Thanks a lot!

Version 3.0.5 of extension is released.

**Comment by web-it-solutions** [comment]
Thank you for super-fast merging. Works like a charm now ;-)
