### ISSUE TITLE
Frontend login form broken in Typo3 v11

### ISSUE THREAD

**Issue by jwtue** [cdaecke/md_saml#19]
Using the frontend login fails loading the login page with the following error message:
`Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\FormViewHelper: requestToken.`

The `requestToken` was added in Typo3 v12 and is not available in v11.

Seems like adding it in f90117dd3e6b4ee81521ffac5803d294bc65463c accidentally dropped support for v11 as well (at least partially).

As a workaround, one can probably use his own `Login.html`-Template with the requestToken removed.

**Comment by cdaecke** [comment]
You are absolutely right. The extension > v3 is only compatible with TYPO3 v12 (constraints are fixed in v3.0.3 ). Please use version 2.0.0 for TYPO3 v11.

Sorry for any inconvenience!
