### ISSUE TITLE
Redirecting to base url, not to calling url

### ISSUE THREAD

**Issue by githubUser123444** [cdaecke/md_saml#2]
First of all thanks for the great Extension!

One thing that the extension seems to be missing is supporting the response URL. 
When logging in via the idp the extension keeps sending me to the base url of my website, not to the calling url. 
Instead of being redirected to mywebsite.com/login, i am redirected to mywebsite.com
Am i missing some configuration?

Thanks in advance

**Comment by cdaecke** [comment]
You are able to configure the returning url in Typoscript (`assertionConsumerService.url`):

Frontend users:
https://github.com/cdaecke/md_saml/blob/c50b1afa598aba7bf86b5fab902ef6840d5ed250/Configuration/TypoScript/setup.typoscript#L34-L41

Backend user:
https://github.com/cdaecke/md_saml/blob/c50b1afa598aba7bf86b5fab902ef6840d5ed250/Configuration/TypoScript/setup.typoscript#L10-L14

**Comment by cdaecke** [comment]
I consider this issue as resolved.
If you have more questions, just open a new issue.
