### ISSUE TITLE
PHP Warning: Undefined array key "username"

### ISSUE THREAD

**Issue by jonathanscholz-snd** [cdaecke/md_saml#22]
Hello,

we tried to configure your extension for SAML Authentication with Microsoft Entra ID but ran into issues with the username.
We included username as a claim in Azure but still got the following error when trying to log in:
PHP Warning: Undefined array key "username" in /var/www/website/vendor/mediadreams/md_saml/Classes/Authentication/SamlAuthService.php line 195

We tried adding the username key as a constant in the php code and it worked, but we are unsure how to dynamically insert the correct claim from the saml response.

Thanks for any help!

**Comment by cdaecke** [comment]
Which version of the extension are you using?

Maybe this helps?
https://github.com/cdaecke/md_saml/blob/master/Readme.md#sso

**Comment by jonathanscholz-snd** [comment]
Thanks for your fast reply.
We are using Typo3 12.4 with Extension Version 3.0.5. 

We managed to resolve the issue with the help of the documentation!

Unfortunately we ran into another issue. When logging in via SAML the user gets redirected to the login page again (/typo3/login?loginProvider=1648123062&login-provider=md_saml&login_status=login&acs). 

In the logs we see: "Login-attempt from <IP-Adress> for username '' with an empty password!"

Do you have an idea what could be the Issue?

**Comment by h0Lz404** [comment]
Hey there,

we are getting the same error using TYPO3 11.5:

> In the logs we see: "Login-attempt from for username '' with an empty password!"

Do you have a solution meanwhile?

**Comment by jonathanscholz-snd** [comment]
Unfortunately not and we have no idea where to look.

**Comment by jonathanscholz-snd** [comment]
Hello again,

we found a solution for out problem: 
In the setup.typoscript when you configure the saml extension we had to remove every entry in the "databaseDefaults" section.
It seems that in that section you can configure the default fields for new user in the database, so choose them only if you need them.

Hope this helps!
