### ISSUE TITLE
Single Logout Service not working in backend

### ISSUE THREAD

**Issue by jwtue** [cdaecke/md_saml#24]
Hello, I found out that while the logout is transferred to the IDP's SLO page correctly in frontend, it isn't performed in backend at all. 

This section here works only on frontend:
https://github.com/cdaecke/md_saml/blob/d0deab6b88f058ae1c3bbb41b484b15b1d3d45ff/Classes/EventListener/SamlBeforeUserLogoutEventListener.php#L21-L29
The `md_saml_source` column is only created by the extension (and set during login) for the `fe_users` table, not for the `be_users`, so the if-condition is always `false`.

Therefore, as `$settingsService->setInCharge(true)` isn't called on backend logout, the code responsible for passing on the logout to the IDP is never called (also, it has the 'fe'-config loaded with no way of using 'be' instead):
https://github.com/cdaecke/md_saml/blob/d0deab6b88f058ae1c3bbb41b484b15b1d3d45ff/Classes/EventListener/SamlAfterUserLoggedOutEventListener.php#L20-L26

**My suggestion for fixing this:**

You could add the `md_saml_source` column to `be_users` as well, remove the restriction to 'fe_users' in 
https://github.com/cdaecke/md_saml/blob/d0deab6b88f058ae1c3bbb41b484b15b1d3d45ff/Classes/Authentication/SamlAuthService.php#L235-L237
and in the SamlAfterUserLoggedOutEventListener make the decision to take fe/be through the `$event->getUser()->user_table` which is either `be_users` or `fe_users`.

What do you think?

**Comment by cdaecke** [comment]
Thanks a lot for pointing that out!

The attached commit should fix this. Could you please double check, by installing  the current master of the extension?

**Comment by cdaecke** [comment]
As this is related with #27 I close this issue here.

**Comment by jwtue** [comment]
Tested and confirmed to work (SP-initiated logout from backend notifies IdP about logout). Thank you :)

Return to the BE login page after this may not work properly yet, as stated in #27.
