### ISSUE TITLE
SamlAuthService::updateUser function no longer working correctly due to data type issue

### ISSUE THREAD

**Issue by Bruno86** [cdaecke/md_saml#26]
The SamlAuthService::updateUser function no longer works as expected since this change:

```
if ($localUser[$key] !== $value) {
    $changed = true;
    break;
}
```
Indeed, $value (which comes from the settings) is a string, but $localUser[$key] may have a different type.
For example, $localUser['pid'] is an integer, but in this case $value is a string.
We should not use !== but !=, otherwise this code considers that it is always different and that changed is always true.

**Comment by cdaecke** [comment]
Thanks a lot for pointing that out!
