### ISSUE TITLE
Single Logout Service not working

### ISSUE THREAD

**Issue by jwtue** [cdaecke/md_saml#3]
Hi,
first of all great work for adding frontend support. Works really well.

As far as I can see, the Single Logout Service functionality is not implemented yet, am I correct?
Any plans to implement this in the near future?

Thank you for your work!

**Comment by denis-fisseler** [comment]
Hello,
I just spend quite some time to get the extension working and at the end also noticed that the SingleLogoutService did not work despite being configured correctly. So I checked the code and did not find anything in the extension connecting to the respective functionality in the onelogin library. However, in the readme of the library is a piece of code that demonstrates how to call a SLS. That of course does not cover the Typo3 integration. If I figure out, how to make it work, I'll post the solution here.

Best regards.

**Comment by cdaecke** [comment]
I have just merged a pull request which adds the single logout service.

@JW301 @denis-fisseler Are you able to test the current master branch?

**Comment by cdaecke** [comment]
v3.0.0 is released, which incorporates the single logout service.

Thanks to @abplana !
