### ISSUE TITLE
Possibility to change default login

### ISSUE THREAD

**Issue by DerVolli** [cdaecke/md_saml#30]
Hi,

is it possible to switch the default login provider? By default I get username/password while I strongly prefer to get the view with the SAML login provider (i.e. view with "Single Sign-on with SAML" and Sign-On-Button).
(I know that i could remove username/password - but I want to keep both!)

Best regards,
Stefan Beck

**Comment by DerVolli** [comment]
Nevermind - found out myself:

see the setup.typoscript:

[....]
        // If you need to specify requested attributes, set a
        // attributeConsumingService. nameFormat, attributeValue and
        // friendlyName can be omitted. Otherwise remove this section.
        attributeConsumingService {
          **isDefault = true,**
          serviceName = SP MdSaml,
          serviceDescription = SAML Service of ext:md_saml
          requestedAttributes {
            10 {
              name = emailAddress
              isRequired = false
              nameFormat = urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified
              friendlyName = mail
              attributeValue = typo3@uni-passau.de
            }
          }
        }
[...]

**Comment by DerVolli** [comment]
Sorry, was not the solution. Still get the username/password mask first

**Comment by cdaecke** [comment]
**Frontend login:**
https://github.com/cdaecke/md_saml/blob/e76f25d487616061102cce41aba32eebfb409478/Readme.md?plain=1#L49-L52

**TYPO3 login**
https://github.com/cdaecke/md_saml/blob/e76f25d487616061102cce41aba32eebfb409478/Readme.md?plain=1#L239-L245

Does this answer your question?

**Comment by cdaecke** [comment]
So you are talking about the backend login?

This can be changed with adding the following line in the `ext_localconf.php` of your own extension:

`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['backend']['loginProviders'][1648123062]['sorting'] = 60;`

**Comment by DerVolli** [comment]
Yes. The BE login.
I added the line - but no effect. We are using btw version 2.0.0 as we still have Typo3 10.4.44
This is our ext_localconf.php:
<?php
defined('TYPO3') or die();

call_user_func(function () {
    /**
     * Register the auth service
     */
    \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addService(
        'md_saml',
        'auth',
        \Mediadreams\MdSaml\Authentication\SamlAuthService::class,
        [
            'title' => 'BE ADFS Authentication',
            'description' => 'Authentication with a Microsoft ADFS',
            'subtype' => 'authUserFE, getUserFE, authUserBE, getUserBE',
            'available' => true,
            'priority' => 80,
            'quality' => 80,
            'os' => '',
            'exec' => '',
            'className' => \Mediadreams\MdSaml\Authentication\SamlAuthService::class
        ]
    );

    $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['backend']['loginProviders'][1648123062] = [
        'provider' => \Mediadreams\MdSaml\LoginProvider\SamlLoginProvider::class,
        'sorting' => 50,
        'icon-class' => 'fa-sign-in',
        'label' => 'LLL:EXT:md_saml/Resources/Private/Language/locallang.xlf:login.md_saml'
    ];

    $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['backend']['loginProviders'][1648123062]['sorting'] = 60;

});
require \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('md_saml') . 'Resources/Libraries/vendor/autoload.php';



    Am Mittwoch, 24. April 2024 um 06:33:27 MESZ hat chris ***@***.***> Folgendes geschrieben:  
 
 


So you are talking about the backend login?

This can be changed with adding the following line in the ext_localconf.php of your own extension:

$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['backend']['loginProviders'][1648123062]['sorting'] = 60;

**Comment by cdaecke** [comment]
Did you clear the TYPO3 cache?

**Comment by DerVolli** [comment]
No - but this helped, thanks a lot! Now it can be really closed ;)

    Am Mittwoch, 24. April 2024 um 08:15:24 MESZ hat chris ***@***.***> Folgendes geschrieben:  
 
 


Did you clear the TYPO3 cache?
