### ISSUE TITLE
How to completely disable Backend SAML login?

### ISSUE THREAD

**Issue by juergen-venne** [cdaecke/md_saml#5]
I just need the frontend SAML login, not the backend login.
plugin.tx_mdsaml.be_users >
has no effect. I still see the Login-Provider.

**Comment by juergen-venne** [comment]
To disable the backend-login I put this in my sitepackage:
ext_localconf.php:
```
// completely remove backend SAML login provider of EXT:md_saml
unset($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['backend']['loginProviders'][1648123062]);
```
composer.json:
```
"require": {
    "mediadreams/md_saml": "*"
},
```

**Comment by cdaecke** [comment]
Yes, that's the way to go.
