### ISSUE TITLE
No creation of entry in fe_users

### ISSUE THREAD

**Issue by Padina14** [cdaecke/md_saml#6]
I'm having trouble getting the extension to work.

observed behavior.
Click on the login button (front end). The Microsoft Teams login mask appears and I log in. I will be redirected to the login page (settings). Switch to a test page. The content element with property 'hide on login' is displayed. The content element with property 'show on any login' is NOT displayed. No Exception occurs.
Logging in again leads directly to the login page. No call of the teams-mask. The login mask is NOT called up again.
In the TYPO3-Backend, no user frontend-user is created. The option `createIfNotExist=1` in typoscript is set.

Expected Behavior
After the login process, the content item with property 'hide on login' will NOT be displayed. The content element with property 'show on any login' is displayed.

Question:
I am looking for suggestions, what I do wrong.
Are there any log-messages that I can use.
Is there any good strategy to find my configuration-mistakes?

P.S.: If I directly call the teams-login, the login works fine.

**Comment by cdaecke** [comment]
Maybe you can post your solution for other here?
