### ISSUE TITLE
Extendibility / Method visibility

### ISSUE THREAD

**Issue by benwalch** [cdaecke/md_saml#7]
Thank you for this package.

Please don't use `private` methods in your classes.
This makes overriding almost impossible. Better practise is to use `protected`.

In my case, I wanted to customize the method `getUserArrayForDb` which is not possible.

Additionally, providing events for customization would be a good way, e.g. after the user data is collected.
 I could make a PR if needed.

**Comment by benwalch** [comment]
i see, there is already a fork which implements more stuff (not the method visibility, but update existing users, including an event):
https://github.com/internetgalerie/md_saml

**Comment by cdaecke** [comment]
Thanks for your contribution, which I have merged.

I will ask, if the guys at [internetgalerie](https://github.com/internetgalerie/md_saml) are interested that I merge their changes as well. After that, I will create a new release.
